name: Angular CI/CD

on:
  push:
    branches:
      - dev 


jobs:
  build:
    runs-on: ubuntu-latest
# on:
#   push:
#     tags:
#       - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
   

# jobs:
#   build:
#     if: github.ref_name == 'refs/heads/new-feature'

#     runs-on: ubuntu-latest
    

#     steps:

#       - name: Print GitHub Context Variables
#         run: |
#           echo "github.ref: $GITHUB_REF"
#           echo "github.ref_name: $GITHUB_REF_NAME"
#           echo "github.base_ref: $GITHUB_BASE_REF"
#           echo "github.event_name: $GITHUB_EVENT_NAME"
#           echo "github.head_ref: $GITHUB_HEAD_REF"
#           echo "github.event.base_ref: $GITHUB_EVENT_BASE_REF"

#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20
#           cache: npm

#       - name: Install dependencies
#         run: npm i --legacy-peer-deps

#       - name: Cache dependencies
#         uses: actions/cache@v4

#       - name: Build Angular app
#         run: npm run build -- --configuration=production

#       - name: Upload build artifacts
#         uses: actions/upload-artifact@v4
#         with:
#           name: angular-dist
#           path: dist/
