name: Angular CI/CD

on:
  push:
    tags:
      - "prod-*"
  

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.ref_name == 'new-feature'

    steps:
      - name: Print GitHub Context Variables
        run: |
          echo "github.ref: $GITHUB_REF"
          echo "github.ref_name: $GITHUB_REF_NAME"
          echo "github.base_ref: $GITHUB_BASE_REF"
          echo "github.event_name: $GITHUB_EVENT_NAME"
          echo "github.head_ref: $GITHUB_HEAD_REF"
          echo "github.event.base_ref: $GITHUB_EVENT_BASE_REF"

      - name: Find the branch where the tag was created
        id: find_branch
        run: |
          git fetch --all
          BRANCH_NAME=$(git log --decorate --oneline | grep ${{ github.ref_name }} | grep -o 'origin/[^,)]*' | awk -F'/' '{print $2}')
          echo "Branch name: $BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Print Debug Info
        run: |
          echo "GitHub ref: $GITHUB_REF"
          echo "GitHub ref name: $GITHUB_REF_NAME"
          echo "Detected branch: $BRANCH_NAME"

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history to check the branch

      - name: Verify tag is from main branch
        run: |
          TAG_NAME=${{ github.ref_name }}  # e.g., v1.0.0
          BRANCH=$(git branch -r --contains tags/$TAG_NAME | grep -E 'origin/new-feature$')
          if [ -z "$BRANCH" ]; then
              echo "Error: Tag $TAG_NAME is not from the new-feature branch!"
              exit 1
          else
              echo "Tag $TAG_NAME is confirmed to be from new-feature branch."
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm i --legacy-peer-deps

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: npm-cache-${{ hashFiles('package-lock.json') }}

      - name: Build Angular app
        run: npm run build -- --configuration=development

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: angular-dist
          path: dist/
